### ISSUE TITLE
Team Project Review

### ISSUE THREAD

**Issue by johnoliver42** [johnoliver42/team-code-defy#1]
@pawaitemadisoncollege 

We have finally decided what we would like to do for the team project.

**Comment by pawaitemadisoncollege** [comment]
Hi Team, you have a good start here, and I think your project idea at its core will provide you with good experience building a RESTful api.

Following are some next steps to consider:

1. Determine how you will track all the tasks that need to be accomplished and who is doing what. You could do this in a markdown document, GitHub Issues, or a tool like Trello. 
2. [Design your api](https://restfulapi.net/rest-api-design-tutorial-with-example/) - in reviewing your problem statement it seems like resources might include a ReadingList and Books.  Document this detail, the fields/properties your Resources will have and the HTTP verbs you will support in your readme.md. Consider what you can cut if need to scale things back.
3. List out all the tasks you need to do in the tool you choose in item 1 above. I'd be happy to review 2 and 3 when you have them ready.
4. Start executing the plan!

**Comment by pawaitemadisoncollege** [comment]
One more thing - On the readme.md and related to scope - document the response formats that your service will provide:  Plain text, json, xml, html, etc? You don't need to do all of them, just plan ahead for what you will do.

**Comment by johnoliver42** [comment]
@pawaitemadisoncollege  We have now added code/documents for each of the issues you mentioned.

**Comment by pawaitemadisoncollege** [comment]
Looks like some good progress @johnoliver42 @shanda-matc @kailynangelo!  Based on the api design doc - are you planning on json as the response format? Having one format is ok, I'm just verifying because the format and http verbs at the bottom of this [page](https://github.com/johnoliver42/team-code-defy/blob/main/design/APIDesign.md) were empty when I reviewed it. 

Do you have any blockers at this point? What is your target completion date? I'm worried this is intruding on your indie project dev time :)

**Comment by johnoliver42** [comment]
Our current target for completion is the beginning of next week if not a bit sooner. 

Current blockers: 

- I discovered I will need to refactor my code because most commands require that the reading order of books be updated.
- One person is currently sick.

**Comment by pawaitemadisoncollege** [comment]
Thanks for the update @johnoliver42. If there's anything I can help with related to blockers please let me know. Hopefully the lack of a late penalty helps with the illness situation!
